Added Twilio API for Form
StayWokeOrg/intake pull request #11
Opened 2017-01-10 01:40 UTC by dougblackjr

Connects to Twilio API. On form submit, will send welcome text message to person completing form. Initial work, just a start for what we need.

2017-01-10 02:57 UTC, mattstauffer submitted a review, later dismissed
@dougblackjr Looks like a solid start--do you know how to do tests in Express? Feels like we should shoot for as much test coverage up front as possible so the desired functionality is clear to new devs who join the project.

2017-01-10 11:26 UTC, dougblackjr commented
@mattstauffer, I don't know much about Node, just started learning it this week tbh. I updated the SMS to match more of what we're trying to do (url/sms, text "woke" to ###, receive response). It's basic, but it'll get us started. Let me know what's next.

2017-01-10 14:11 UTC, pascalpp requested changes
Some code style changes and some conflicts to resolve.

2017-01-10 14:11 UTC, pascalpp commented on public/index.html
> +                <form onsubmit="return false;">
This no-op change is causing a conflict with other changes that have already merged out. Can you remove this semi-colon?

2017-01-10 14:11 UTC, pascalpp commented on index.js
> +var ngrok = require('ngrok');
`const`

2017-01-10 14:11 UTC, pascalpp commented on index.js
> +var smsController = require('./controllers/sms.controller');
`const`

2017-01-10 14:11 UTC, pascalpp commented on index.js
> +  .post(smsController.receiveWoke);
we're not using semi-colons in this repo. (i need to setup a lint:fix cmd so it's easy to keep this consistent.) Can you remove semicolons here and merge the upstream development branch and resolve and conflicts? Let me know if you have any questions about the upstream changes.

2017-01-10 22:59 UTC, dougblackjr commented on public/index.html
> +                <form onsubmit="return false;">
Done on next commit.

2017-01-10 23:12 UTC, dougblackjr commented on index.js
> +  .post(smsController.receiveWoke);
Fixed in next commit

2017-01-10 23:12 UTC, dougblackjr commented on index.js
> +var smsController = require('./controllers/sms.controller');
Fixed in next commit

2017-01-10 23:24 UTC, dougblackjr reviewed
Errors fixed on newest commit

2017-01-10 23:24 UTC, dougblackjr reviewed
I'm not terribly familiar with testing, as I'm new to node.js. I may not be of help here at this point.

2017-01-10 23:25 UTC, dougblackjr commented
I made changes in the newest commits. Let me know your thoughts, @mattstauffer @pascalpp

2017-01-11 00:33 UTC, pascalpp requested changes
this is looking good. I still need to try it out. Couple of minor changes.

2017-01-11 00:33 UTC, pascalpp commented on index.js
> +const dotenv = require('dotenv')
dotenv needs to be initialized before other modules, notably `debug`, which is why i put it first in the file. can you move this require back to the top?

2017-01-11 00:33 UTC, pascalpp commented on index.js
> +dotenv.load()
and these two lines back up top as well.

2017-01-11 01:26 UTC, dougblackjr reviewed
Fixed on newest commit

2017-01-11 01:28 UTC, pascalpp approved these changes

2017-01-11 19:00 UTC, merged